// Generated by CoffeeScript 1.6.3
(function() {
  var MyClass;

  MyClass = (function() {
    function MyClass(d) {
      $.extend(this, d);
    }

    MyClass.prototype.apple = {};

    return MyClass;

  })();

  window.MyClass = MyClass;

}).call(this);
