// Generated by CoffeeScript 1.6.3
(function() {
  var $, CollectionFactory, IndustryCollection, IndustryModel, ModelFactory, _ref, _ref1,
    __slice = [].slice,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  IndustryModel = (function() {
    function IndustryModel() {}

    IndustryModel.prototype.traits = {};

    IndustryModel.prototype._data = {};

    IndustryModel.prototype._base = function() {
      return {};
    };

    IndustryModel.prototype._klass = false;

    IndustryModel.prototype.trait = function(name, afunc) {
      return this.traits[name] = afunc;
    };

    IndustryModel.prototype.data = function(options) {
      if (typeof options === 'function') {
        return this._base = options;
      } else {
        return this._data = $.extend({}, this._data, options);
      }
    };

    IndustryModel.prototype.klass = function(obj) {
      return this._klass = obj;
    };

    IndustryModel.prototype.create = function() {
      var data, i, key, trait, traits, val, _i, _len;
      data = arguments[0], traits = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      if (data === null) {
        data = {};
      }
      data = $.extend({}, this._data, this._base(), data);
      for (i = _i = 0, _len = traits.length; _i < _len; i = ++_i) {
        trait = traits[i];
        if (this.traits[trait]) {
          data = $.extend({}, data, this.traits[trait].apply(this, []));
        }
      }
      for (key in data) {
        val = data[key];
        if (typeof val === 'function') {
          data[key] = val();
        }
      }
      if (this._klass) {
        data = new this._klass(data);
      }
      return data;
    };

    return IndustryModel;

  })();

  IndustryCollection = (function(_super) {
    __extends(IndustryCollection, _super);

    function IndustryCollection() {
      _ref = IndustryCollection.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    IndustryCollection.prototype.create = function() {
      var collection, count, data, i, model, traits, _i, _klass;
      data = arguments[0], count = arguments[1], model = arguments[2], traits = 4 <= arguments.length ? __slice.call(arguments, 3) : [];
      if (data === null) {
        data = {};
      }
      _klass = this._klass;
      this._klass = false;
      data = IndustryCollection.__super__.create.apply(this, [data].concat(__slice.call(traits)));
      this._klass = _klass;
      if (!count) {
        count = 5;
      }
      collection = [];
      for (i = _i = 1; 1 <= count ? _i <= count : _i >= count; i = 1 <= count ? ++_i : --_i) {
        collection.push(model.create.apply(model, [data].concat(__slice.call(traits))));
      }
      if (this._klass) {
        collection = new this._klass(collection);
      }
      return collection;
    };

    return IndustryCollection;

  })(IndustryModel);

  ModelFactory = (function() {
    function ModelFactory() {}

    ModelFactory.prototype.klass = IndustryModel;

    ModelFactory.prototype.define = function(options, callback) {
      var instance, name, trait, _ref1, _ref2;
      instance = new this.klass;
      if (!callback && typeof options === 'function') {
        callback = options;
      } else if (typeof options === 'object') {
        if (options.parent) {
          instance.base(options.parent._base);
          instance.data(options.parent._data);
          instance.klass(options.parent._klass);
          _ref1 = options.parent.traits;
          for (name in _ref1) {
            trait = _ref1[name];
            instance.trait(name, trait);
          }
        }
        if (options.base) {
          instance.data(options.base);
        }
        if (options.traits) {
          _ref2 = options.traits;
          for (name in _ref2) {
            trait = _ref2[name];
            instance.trait(name, options.traits[key]);
          }
        }
        if (options.klass) {
          instance.klass(options.klass);
        }
      }
      if (typeof callback === 'function') {
        callback(instance);
      }
      return instance;
    };

    return ModelFactory;

  })();

  CollectionFactory = (function(_super) {
    __extends(CollectionFactory, _super);

    function CollectionFactory() {
      _ref1 = CollectionFactory.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    CollectionFactory.prototype.klass = IndustryCollection;

    return CollectionFactory;

  })(ModelFactory);

  if (typeof window !== 'undefined') {
    window.IndustryModel = new IndustryModel;
    window.IndustryCollection = new IndustryCollection;
    window.ModelFactory = new ModelFactory;
    window.CollectionFactory = new CollectionFactory;
  } else if (typeof module !== 'undefined') {
    $ = require('jquery');
    module.exports.IndustryModel = new IndustryModel;
    module.exports.IndustryCollection = new IndustryCollection;
    module.exports.ModelFactory = new ModelFactory;
    module.exports.CollectionFactory = new CollectionFactory;
  }

}).call(this);
