// Generated by CoffeeScript 1.6.3
(function() {
  var IndustryCollection, IndustryFactory, IndustryModel, TraitSelection, extend, upStart,
    __slice = [].slice,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  IndustryModel = (function() {
    function IndustryModel(data) {
      this._traits = {};
      this._traits_args = {};
      this._data = [];
      this._klass = false;
      this._klass_callback = [];
    }

    IndustryModel.prototype.sequence = function(name) {
      return IndustryFactory.sequence(name);
    };

    IndustryModel.prototype.trait = function(name, afunc) {
      var _this = this;
      this._traits[name] = afunc;
      if (typeof this[name] === 'undefined') {
        this[name] = function() {
          var args;
          args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
          _this._traits_args[name] = args;
          return _this;
        };
      } else {
        throw "" + name + " is a reserved name.";
      }
      return this;
    };

    IndustryModel.prototype.traits = function(traits, args) {
      if (arguments.length < 1) {
        return this._traits;
      } else if (traits === true) {
        return [this._traits, this._traits_args];
      }
      this._traits = extend({}, this._traits, traits);
      if (typeof args !== 'undefined') {
        this._traits_args = extend({}, this._traits_args, args);
      }
      return this;
    };

    IndustryModel.prototype.data = function(input) {
      if (arguments.length < 1) {
        return this._data;
      }
      if (Object.prototype.toString.call(input) === '[object Array]') {
        this._data = this._data.concat(input);
      } else if (typeof input === 'function' || typeof input === 'object') {
        this._data.push(input);
      }
      return this;
    };

    IndustryModel.prototype.klass = function(obj, callback) {
      if (typeof obj === 'function' || obj === false) {
        this._klass = obj;
      }
      this.klass_callback(callback);
      return this;
    };

    IndustryModel.prototype.klass_callback = function(callback) {
      var item, _i, _len;
      if (callback === false || callback === 'reset') {
        this._klass_callback = [];
      }
      if (Object.prototype.toString.call(callback) !== '[object Array]') {
        callback = [callback];
      }
      for (_i = 0, _len = callback.length; _i < _len; _i++) {
        item = callback[_i];
        if (typeof item === 'function') {
          this._klass_callback.push(item);
        }
      }
      return this;
    };

    IndustryModel.prototype.create = function() {
      var callback, data, item, key, traits, val, _i, _j, _len, _len1, _ref, _ref1,
        _this = this;
      traits = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      data = {};
      _ref = this._data;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        item = _ref[_i];
        if (typeof item === 'function') {
          item = item.call(this);
        }
        data = extend({}, data, item);
      }
      new TraitSelection(this).each(traits, function(trait, d) {
        return data = extend({}, data, trait.apply(_this, d));
      });
      for (key in data) {
        val = data[key];
        if (typeof val === 'function') {
          data[key] = val.call(this);
        }
      }
      if (this._klass !== false) {
        data = new this._klass(data);
        _ref1 = this._klass_callback;
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          callback = _ref1[_j];
          if (typeof callback === 'function') {
            data = callback.call(this, data);
          }
        }
      }
      return data;
    };

    return IndustryModel;

  })();

  IndustryCollection = (function(_super) {
    __extends(IndustryCollection, _super);

    function IndustryCollection() {
      this._model_callback = [];
      this._model = false;
      IndustryCollection.__super__.constructor.apply(this, arguments);
    }

    IndustryCollection.prototype.model = function(m) {
      this._model = m;
      return this;
    };

    IndustryCollection.prototype.model_callback = function(callback) {
      var item, _i, _len;
      if (callback === false || callback === 'reset') {
        this._model_callback = [];
      }
      if (Object.prototype.toString.call(callback) !== '[object Array]') {
        callback = [callback];
      }
      for (_i = 0, _len = callback.length; _i < _len; _i++) {
        item = callback[_i];
        if (typeof item === 'function') {
          this._model_callback.push(item);
        }
      }
      return this;
    };

    IndustryCollection.prototype.create = function() {
      var argument, callback, collection, count, data, i, traits, _i, _j, _k, _klass, _len, _len1, _ref, _ref1;
      count = 5;
      traits = [];
      for (_i = 0, _len = arguments.length; _i < _len; _i++) {
        argument = arguments[_i];
        if (typeof argument === 'number') {
          count = argument;
        } else {
          traits.push(argument);
        }
      }
      _klass = this._klass;
      this._klass = false;
      data = IndustryCollection.__super__.create.call(this);
      this._klass = _klass;
      collection = [];
      if (typeof this._model === 'undefined' || !this._model) {
        throw "No model for collection";
      } else {
        if (count > 0) {
          for (i = _j = 1; 1 <= count ? _j <= count : _j >= count; i = 1 <= count ? ++_j : --_j) {
            this._model.klass_callback(this._model_callback);
            this._model.traits(this._traits, this._traits_args);
            this._model.data(data);
            collection.push((_ref = this._model).create.apply(_ref, traits));
          }
        }
      }
      if (this._klass !== false) {
        collection = new this._klass(collection);
        _ref1 = this._klass_callback;
        for (_k = 0, _len1 = _ref1.length; _k < _len1; _k++) {
          callback = _ref1[_k];
          if (typeof callback === 'function') {
            collection = callback.call(this, collection);
          }
        }
      }
      return collection;
    };

    return IndustryCollection;

  })(IndustryModel);

  IndustryFactory = (function() {
    var define, klass, sequences;

    function IndustryFactory() {}

    klass = IndustryModel;

    sequences = {};

    define = function(options, callback) {
      var args, instance;
      instance = new klass;
      if (!callback && typeof options === 'function') {
        callback = options;
      } else if (typeof options === 'object') {
        if (options.parent) {
          instance.data(options.parent._base);
          instance.data(options.parent._data);
          instance.traits(options.parent._traits);
          instance.klass(options.parent._klass);
          instance.klass_callback(options.parent._klass_callback);
          if (typeof options.parent._model_callback !== 'undefined') {
            instance.model_callback(options.parent._model_callback);
          }
        }
        if (options.data) {
          instance.data(options.data);
        }
        if (options.traits) {
          instance.traits(options.traits);
        }
        if (options.klass) {
          args = [options.klass];
          if (options.klass_callback) {
            args.push(options.klass_callback);
          }
          instance.klass.apply(instance, args);
        } else if (options.klass_callback) {
          instance.klass_callback(options.klass_callback);
        }
        if (options.model) {
          instance.model(options.model);
        }
      }
      if (typeof callback === 'function') {
        callback(instance);
      }
      return instance;
    };

    IndustryFactory.sequence = function(name) {
      if (typeof sequences[name] === 'undefined') {
        return sequences[name] = 1;
      } else {
        return ++sequences[name];
      }
    };

    IndustryFactory.defineCollection = function() {
      klass = IndustryCollection;
      return define.apply(this, arguments);
    };

    IndustryFactory.defineModel = function(options, callback) {
      klass = IndustryModel;
      return define.apply(this, arguments);
    };

    return IndustryFactory;

  })();

  TraitSelection = (function() {
    TraitSelection.obj = false;

    function TraitSelection(obj) {
      this.obj = obj;
    }

    TraitSelection.prototype.each = function(traits, callback) {
      var args, name, option_tool, options, trait, trait_names, _i, _len, _results;
      trait_names = [];
      _results = [];
      for (_i = 0, _len = traits.length; _i < _len; _i++) {
        trait = traits[_i];
        options = trait.split(':');
        name = options.shift();
        trait_names.push(name);
        trait = this.obj._traits[name];
        args = this.obj._traits_args[name];
        if (typeof trait !== 'undefined') {
          option_tool = {
            getObj: function() {
              return obj;
            },
            hasTrait: function(name) {
              return trait_names.indexOf(name) !== -1;
            },
            hasOption: function() {
              return this.hasOptions.apply(this, arguments);
            },
            hasOptions: function() {
              var input, option, result, _j, _len1;
              input = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
              if (options.length < 1) {
                return false;
              }
              if (options.indexOf('all!') !== -1) {
                return true;
              }
              result = true;
              for (_j = 0, _len1 = input.length; _j < _len1; _j++) {
                option = input[_j];
                result = result && options.indexOf(option) !== -1;
              }
              return result;
            }
          };
          _results.push(callback(trait, [option_tool].concat(args)));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    return TraitSelection;

  })();

  extend = function() {
    var args, _ref, _ref1;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    if (typeof window !== 'undefined' && typeof window.$ !== 'undefined') {
      return (_ref = window.$).extend.apply(_ref, args);
    } else if (typeof window !== 'undefined' && typeof window._ !== 'undefined') {
      return (_ref1 = window._).extend.apply(_ref1, args);
    } else if (typeof window === 'undefined' && typeof global.$ !== 'undefined') {
      return $.extend.apply($, args);
    } else if (typeof window === 'undefined' && typeof global._ !== 'undefined') {
      return _.extend.apply(_, args);
    } else {
      throw "Underscore.js or jQuery is required.";
    }
  };

  upStart = function() {
    if (typeof window === 'undefined') {
      global._ = require('underscore');
    }
    if (typeof window === 'undefined') {
      module.exports.industry = IndustryFactory;
    }
    if (typeof window !== 'undefined') {
      return window.industry = IndustryFactory;
    }
  };

  upStart();

}).call(this);
