// Generated by CoffeeScript 1.6.3
(function() {
  var $, MyClass;

  MyClass = (function() {
    function MyClass(d) {
      $.extend(this, d);
    }

    MyClass.prototype.apple = {};

    return MyClass;

  })();

  if (typeof window !== 'undefined') {
    window.MyClass = MyClass;
  } else if (typeof module !== 'undefined') {
    $ = require('jquery');
    module.exports.MyClass = new MyClass;
  }

}).call(this);
