// Generated by CoffeeScript 1.6.3
(function() {
  var $, MyClass, MyCollection, _;

  MyClass = (function() {
    function MyClass(d) {
      this.data = d;
    }

    MyClass.prototype.data = {};

    return MyClass;

  })();

  MyCollection = (function() {
    function MyCollection(d) {
      this.data = d;
    }

    MyCollection.prototype.getResults = function() {
      return this.data;
    };

    MyCollection.prototype.data = [1, 2, 3, 4, 5];

    return MyCollection;

  })();

  if (typeof window !== 'undefined') {
    window.MyClass = MyClass;
    window.MyCollection = MyCollection;
  } else if (typeof module !== 'undefined') {
    _ = require('underscore');
    module.exports.MyClass = MyClass;
    module.exports.MyCollection = MyCollection;
  }

  if (typeof $ === 'undefined' && typeof _ !== 'undefined') {
    $ = _;
  } else if (typeof $ === 'undefined' && typeof _ === 'undefined') {
    throw "Underscore.js or jQuery is required.";
  }

}).call(this);
